# Generated by Django 4.0.6 on 2022-07-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26, unique=True, verbose_name='이름')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='나이')),
                ('weight', models.CharField(max_length=30, verbose_name='체급')),
                ('total', models.IntegerField(verbose_name='전')),
                ('win', models.IntegerField(verbose_name='승')),
                ('lose', models.IntegerField(verbose_name='패')),
                ('draw', models.IntegerField(verbose_name='무승부')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='수상')),
            ],
            options={
                'verbose_name': '선수소개',
                'verbose_name_plural': '선수소개',
                'db_table': 'boxer_info',
            },
        ),
    ]
