# Generated by Django 4.0.6 on 2022-07-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxerinfo',
            name='age',
            field=models.DateTimeField(blank=True, null=True, verbose_name='나이'),
        ),
    ]
