# Generated by Django 4.0.6 on 2022-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxer', '0002_alter_boxerinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxerinfo',
            name='age',
            field=models.DateTimeField(blank=True, max_length=8, null=True, verbose_name='나이'),
        ),
    ]
