# Generated by Django 4.0.6 on 2022-07-22 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(max_length=30, unique=True, verbose_name='안내사항')),
            ],
        ),
        migrations.CreateModel(
            name='TimeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작시간')),
                ('end_time', models.TimeField(verbose_name='종료시간')),
                ('note', models.CharField(max_length=200, verbose_name='비고')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.info', verbose_name='이용시간')),
            ],
        ),
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_period', models.CharField(max_length=20, verbose_name='등록기간')),
                ('price', models.IntegerField(verbose_name='회비')),
                ('note', models.CharField(max_length=200, verbose_name='비고')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.info', verbose_name='요금안내')),
            ],
        ),
    ]
