# Generated by Django 4.0.6 on 2022-07-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeinfo',
            options={'verbose_name': '이용시간', 'verbose_name_plural': '이용시간'},
        ),
        migrations.AlterField(
            model_name='timeinfo',
            name='note',
            field=models.CharField(max_length=200, null=True, verbose_name='비고'),
        ),
        migrations.AlterModelTable(
            name='timeinfo',
            table='timeinfo',
        ),
    ]
