# Generated by Django 4.0.6 on 2022-07-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_timeinfo_options_alter_timeinfo_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceinfo',
            options={'verbose_name': '요금안내', 'verbose_name_plural': '요금안내'},
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='timeinfo',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='비고'),
        ),
        migrations.AlterModelTable(
            name='priceinfo',
            table='priceinfo',
        ),
    ]
